### ISSUE TITLE
 Tests 5, 6, 7, and 10's solutions do not pass

### ISSUE THREAD

**Issue by Fraih001** [testbrew/testbrew#10]

**Comment by Fraih001** [comment]
currently working on

**Comment by Fraih001** [comment]
This PR fixes this issue: https://github.com/testbrew/testbrew/pull/32#issue-1523224307

**Comment by bob-zs** [comment]
Please close issues after their merged. The PRs still need to be tested and approved. 
You can close them after you merge them.

Otherwise, thanks for getting this together and debugging these.
